version: '3'

services:

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    restart: always
    ports: 
      - "8080:80"
    depends_on:
      - app
    networks:
      - node-network
  
  app:
    container_name: app
    restart: always
    build:
      context: ./node
    depends_on:
      db:
        condition: service_healthy
    networks:
      - node-network

  db:
    build: 
      context: ./mysql
    container_name: db
    restart: always
    tty: true
    networks:
      - node-network
    volumes:
      - ./mysql/volume:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 10s
      retries: 3

networks:
  node-network:
    driver: bridge